const products = [
 {sku:"JPL510",name:'10" Five-Compartment Sugarcane Bagasse Plate',category:"Plates & Bowls",spec:"10 in · Case 500",use:"Multiple-item meals, catering and events"},
 {sku:"JPL310",name:'10" Three-Compartment Sugarcane Bagasse Plate',category:"Plates & Bowls",spec:"10 in · Case 500",use:"Portioned meals, catering and takeout"},
 {sku:"JBWL12",name:"12 oz Sugarcane Bagasse Bowl",category:"Plates & Bowls",spec:"12 oz (360 ml) · Case 1,000",use:"Soups, sides and desserts"},
 {sku:"JPL7",name:'7" Round Sugarcane Bagasse Plates',category:"Plates & Bowls",spec:"7 in · Case 500",use:"Snacks, desserts and light servings"},
 {sku:"JPL9",name:'9" Round Sugarcane Bagasse Plates',category:"Plates & Bowls",spec:"9 in · Case 500",use:"Everyday meals and events"},
 {sku:"JPL10",name:'10" Round Sugarcane Bagasse Plates',category:"Plates & Bowls",spec:"10 in · Case 500",use:"Full meals, catering and gatherings"},
 {sku:"JMF24",name:"24 oz Rectangular Plastic Container",category:"Containers",spec:"24 oz (710 ml) · Case 150",use:"Prepared food, takeaway and meal service"},
 {sku:"J262TW",name:"Food-Grade Plastic Spoons — Medium",category:"Cutlery",spec:"Case 1,000",use:"Everyday food service and events"},
 {sku:"J286TWH",name:"Food-Grade Plastic Spoons — Heavy Duty",category:"Cutlery",spec:"Case 1,000",use:"Catering, takeout and heavier foods"},
 {sku:"JSS600",name:"6 × 6 × 3 in Hinged Bagasse Container",category:"Containers",spec:"Case 400",use:"Compact takeout portions and sides"},
 {sku:"JSS960",name:"9 × 6 × 3 in Hinged Bagasse Container",category:"Containers",spec:"Case 200",use:"Takeout meals and food service"},
 {sku:"JSS900",name:"9 × 9 × 3 in Hinged Bagasse Container",category:"Containers",spec:"Case 200",use:"Full takeout meals and catering"},
 {sku:"J350-08",name:"8 oz Coffee Cups — White Plain",category:"Cups",spec:"Case 1,000",use:"Coffee, tea and hot drinks"},
 {sku:"JPDC09",name:"9 oz Clear Plastic Water Cups",category:"Cups",spec:"12 × 80 pack · Case 960",use:"Cold drinks, offices and events"},
 {sku:"JCW12",name:"12 oz Hot Cup — White Plain",category:"Cups",spec:"Case 1,000",use:"Coffee, tea and hot drinks"},
 {sku:"J261FW",name:"Food-Grade Plastic Fork — Medium",category:"Cutlery",spec:"Case 1,000",use:"Everyday food service and events"},
 {sku:"J285FWH",name:"Food-Grade Plastic Fork — Heavy Duty",category:"Cutlery",spec:"Case 1,000",use:"Catering, takeout and heavier foods"},
 {sku:"JYT08",name:"Deli Plastic Container — White",category:"Containers",spec:"8 oz · Case 240",use:"Deli sides, prepared foods and storage"},
 {sku:"JYT16",name:"Deli Plastic Container — White",category:"Containers",spec:"16 oz · Case 240",use:"Deli foods, takeout and storage"},
 {sku:"JYT32",name:"Deli Plastic Container — White",category:"Containers",spec:"32 oz · Case 240",use:"Larger deli portions and prepared foods"},
 {sku:"JMY900",name:"Round Black Combo Container",category:"Containers",spec:"7 in / 32 oz · Case 150",use:"Meal prep, takeout and presentation"},
 {sku:"JMY650",name:"Round Black Combo Container",category:"Containers",spec:"7 in / 24 oz · Case 150",use:"Meal prep, takeout and presentation"},
 {sku:"JFST-HD",name:"Full Size Aluminum Pan — Deep Heavy Duty",category:"Trays",spec:"Case 50",use:"Catering, baking and bulk food service"},
 {sku:"JFST(S)-HD",name:"Full Size Aluminum Pan — Shallow Heavy Duty",category:"Trays",spec:"Case 50",use:"Catering, warming and food service"},
 {sku:"J2667",name:"6-Piece Cutlery Kit — Medium White",category:"Cutlery",spec:"Case 250",use:"Takeout, catering and packed meals"},
 {sku:"J2668",name:"6-Piece Cutlery Kit — Heavy Duty White",category:"Cutlery",spec:"Case 250",use:"Takeout, catering and packed meals"},
 {sku:"J9931B",name:"1 Comp. 9 × 9 × 3 Hot & Cold Hinged Container",category:"Containers",spec:"Case 150",use:"Full-size takeout meals"},
 {sku:"J8831B",name:"1 Comp. 8 × 8 × 3 Hot & Cold Hinged Container",category:"Containers",spec:"Case 150",use:"Takeout meals and prepared foods"},
 {sku:"J6631",name:"1 Comp. 6 × 6 × 3 Hot & Cold Hinged Container",category:"Containers",spec:"Case 250",use:"Compact takeout portions and sides"},
 {sku:"J962.5",name:"1 Comp. Hinged Hot & Cold Food Container",category:"Containers",spec:"Case 150",use:"Takeout and hot or cold food service"},
 {sku:"PPE-GLV",name:"Nitrile Gloves",category:"PPE & Cleanroom",spec:"Contact us for sizes and availability",use:"Food handling, cleaning and general workplace use",image:"assets/ppe/nitrile-gloves.webp"},
 {sku:"PPE-MSK",name:"Disposable Masks",category:"PPE & Cleanroom",spec:"Contact us for product details",use:"Everyday workplace and hygiene needs",image:"assets/ppe/masks.webp"},
 {sku:"PPE-LBC",name:"Disposable Lab Coats",category:"PPE & Cleanroom",spec:"Contact us for sizes and availability",use:"Clean work areas and general protective wear",image:"assets/ppe/lab-coat.webp"},
 {sku:"PPE-HNT",name:"Disposable Hair Nets",category:"PPE & Cleanroom",spec:"Contact us for product details",use:"Food service, production and clean work areas",image:"assets/ppe/hair-nets.webp"},
 {sku:"PPE-SHC",name:"Disposable Shoe Covers",category:"PPE & Cleanroom",spec:"Contact us for product details",use:"Clean work areas and visitor protection",image:"assets/ppe/shoe-covers.webp"},
 {sku:"PPE-BRD",name:"Disposable Beard Covers",category:"PPE & Cleanroom",spec:"Contact us for product details",use:"Food service, production and clean work areas",image:"assets/ppe/beard-covers.webp"},
 {sku:"PPE-SLV",name:"Disposable Sleeve Covers",category:"PPE & Cleanroom",spec:"Contact us for product details",use:"Food handling and clean work areas",image:"assets/ppe/sleeve-covers.webp"}
].map((p,i)=>({...p,image:p.image||`assets/products/${String(i+1).padStart(2,"0")}.jpg`}));

const catalogue=document.querySelector("#catalogue"), count=document.querySelector("#result-count"), search=document.querySelector("#search"), dialog=document.querySelector("#product-dialog"), dialogContent=document.querySelector("#dialog-content");
let selectedCategory="All", lastFocused=null, hasInteracted=false;
const escapeHtml=value=>String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]);
function filtered(){const q=search.value.trim().toLowerCase();return products.filter(p=>(selectedCategory==="All"||p.category===selectedCategory)&&(!q||`${p.sku} ${p.name} ${p.category} ${p.spec} ${p.use}`.toLowerCase().includes(q)))}
function render(){const shown=filtered();count.textContent=`${shown.length} product${shown.length===1?"":"s"}`;count.setAttribute("aria-live",hasInteracted?"polite":"off");catalogue.innerHTML=shown.length?shown.map(p=>`<article class="product"><button class="product-open" data-sku="${escapeHtml(p.sku)}" aria-label="View details for ${escapeHtml(p.name)}"><div class="product-visual"><img src="${p.image}" alt="${escapeHtml(p.name)}" loading="lazy" decoding="async" width="900" height="900"><b class="badge">${escapeHtml(p.category)}</b></div><div class="product-body"><span class="sku">${escapeHtml(p.sku)}</span><h3>${escapeHtml(p.name)}</h3><p class="meta">${escapeHtml(p.spec)}</p><p class="use">${escapeHtml(p.use)}</p><span class="detail-link">View details →</span></div></button></article>`).join(""):`<p class="empty">No products match your search. Try another term or <a href="#contact">contact us</a>.</p>`}
function openProduct(sku){const p=products.find(x=>x.sku===sku);if(!p)return;lastFocused=document.activeElement;const message=encodeURIComponent(`Hi, I'm interested in ${p.sku} — ${p.name}. Please share availability and details.`);dialogContent.innerHTML=`<div class="dialog-grid"><img src="${p.image}" alt="${escapeHtml(p.name)}" width="900" height="900"><div><span class="sku">${escapeHtml(p.sku)} · ${escapeHtml(p.category)}</span><h2 id="dialog-title">${escapeHtml(p.name)}</h2><dl><div><dt>Product details</dt><dd>${escapeHtml(p.spec)}</dd></div><div><dt>Common use</dt><dd>${escapeHtml(p.use)}</dd></div></dl><p>Contact JIJA Services for availability, options and current pricing.</p><a class="button primary" href="https://wa.me/17325358584?text=${message}" target="_blank" rel="noopener">Ask on WhatsApp ↗</a></div></div>`;dialog.showModal();document.body.classList.add("no-scroll");document.querySelector(".dialog-close").focus()}
document.querySelectorAll(".filters button").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".filters button").forEach(b=>{b.classList.toggle("active",b===btn);b.setAttribute("aria-pressed",String(b===btn))});selectedCategory=btn.dataset.category;hasInteracted=true;render()}));
search.addEventListener("input",()=>{hasInteracted=true;render()});catalogue.addEventListener("click",e=>{const button=e.target.closest(".product-open");if(button)openProduct(button.dataset.sku)});document.querySelector(".dialog-close").addEventListener("click",()=>dialog.close());dialog.addEventListener("click",e=>{if(e.target===dialog)dialog.close()});dialog.addEventListener("cancel",e=>{e.preventDefault();dialog.close()});dialog.addEventListener("close",()=>{document.body.classList.remove("no-scroll");if(lastFocused?.isConnected)lastFocused.focus()});
dialog.addEventListener("keydown",e=>{if(e.key!=="Tab")return;const focusable=[...dialog.querySelectorAll('button:not([disabled]),a[href],input:not([disabled]),[tabindex]:not([tabindex="-1"])')];if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});
const menu=document.querySelector(".menu"),nav=document.querySelector("#nav");function setMenu(open,{returnFocus=false}={}){nav.classList.toggle("open",open);menu.setAttribute("aria-expanded",String(open));if(open)nav.querySelector("a").focus();else if(returnFocus)menu.focus()}menu.addEventListener("click",()=>setMenu(!nav.classList.contains("open")));nav.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>setMenu(false)));document.addEventListener("keydown",e=>{if(e.key==="Escape"&&nav.classList.contains("open"))setMenu(false,{returnFocus:true})});document.addEventListener("click",e=>{if(nav.classList.contains("open")&&!nav.contains(e.target)&&e.target!==menu)setMenu(false)});window.addEventListener("resize",()=>{if(window.innerWidth>900&&nav.classList.contains("open"))setMenu(false)});render();
